---
- name: install bind packages
  apt: pkg={{ item }} state={{ bind_pkg_state }}
  with_items: "{{ bind_pkgs }}"

- name: install rsync
  apt: pkg=rsync state=present

- name: setup zones
  template: src=named.conf.local.{{ item }}.j2 dest={{ bind_config_basepath }}/named.conf.local.{{ item }} owner={{ bind_user }} group={{ bind_group }} mode=0600
  with_items:
   - internal
   - external
  notify: reload bind

- name: configure bind
  copy: src=named.conf dest={{ bind_config_basepath }}/named.conf owner={{ bind_user }} group={{ bind_group }} mode=0600
  notify: restart bind

- name: configure bind options
  template: src=named.conf.options.j2 dest={{ bind_config_basepath }}/named.conf.options owner={{ bind_user }} group={{ bind_group }} mode=0600
  notify: restart bind

- name: Copy zone files
  synchronize: src={{ bind_masterzones_path }} dest={{ bind_base_zones_path }} delete=yes recursive=yes mode=push
  notify: reload bind
  tags: bind-zones
  when: bind_config_internal_master_zones is not none

- name: start/stop bind service
  service: name={{ bind_service_name }} state={{ bind_service_state }} enabled={{ bind_service_enabled }}
