---
- name: restart bind
  service: name={{ bind_service_name }} state=restarted

- name: reload bind
  service: name={{ bind_service_name }} state=reloaded

- name: reload zones
  shell: rndc freeze; rndc reload; rndc thaw

